channels:
- conda-forge
dependencies:
- nbsphinx
- dill
- future
- gitpython
- h5io
- h5py
- numpy
- pandas
- pathlib2
- pint
- psutil
- pyfileindex
- pysqa
- pytables
- sqlalchemy
- tqdm
- traitlets
