channels:
- conda-forge
dependencies:
- cloudpickle =2.0.0
- gitpython =3.1.23
- h5io_browser =0.0.14
- h5py =3.6.0
- jinja2 =2.11.3
- monty =2025.1.3
- numpy =1.23.5
- pandas =2.0.0
- pint =0.18
- psutil =5.8.0
- pyfileindex =0.0.16
- pyiron_dataclasses =0.0.4
- pyiron_snippets =0.1.3
- executorlib =0.1.0
- pysqa =0.1.12
- pytables =3.6.1
- sqlalchemy =2.0.22
- tqdm =4.44.0
- traitlets =5.1.1
- hatchling =1.27.0
- hatch-vcs =0.5.0
