channels:
- conda-forge
dependencies:
- dill =0.3.1.1
- gitpython =3.1.23
- h5io =0.1.2
- h5py =3.6.0
- jinja2 =2.11.3
- numpy =1.23.5
- pandas =2.0.0
- pint =0.18
- psutil =5.8.0
- pyfileindex =0.0.16
- pysqa =0.1.5
- pytables =3.6.1
- python-blosc2 =2.2.9
- sqlalchemy =2.0.22
- tqdm =4.44.0
- traitlets =5.1.1
