channels:
- conda-forge
dependencies:
- python
- conda =25.9.1
- conda_subprocess =0.0.10
- cloudpickle =3.1.2
- executorlib =1.7.3
- gitpython =3.1.45
- h5io_browser =0.2.7
- h5py =3.15.1
- jinja2 =3.1.6
- monty =2025.3.3
- numpy =2.3.5
- pandas =2.3.3
- pint =0.25.1
- psutil =7.2.0
- pyfileindex =0.1.1
- pyiron_dataclasses =0.0.8
- pyiron_snippets =1.0.2
- pysqa =0.3.3
- pytables =3.10.2
- sqlalchemy =2.0.44
- tqdm =4.67.1
- traitlets =5.14.3
- hatchling =1.27.0
- hatch-vcs =0.5.0
